{% set data = load_setuptools() %}

package:
    name: obvious-ci
    version: {{data.get('version')}}

source:
    path: ../

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - setuptools
        - anaconda-client
        - conda
        - conda-build

test:
  imports:
    - obvci
    - obvci.conda_tools
    - obvci.cli
  commands:
    - unset CONDA_NPY && obvci_conda_build_dir --help  # [not win]
    - obvci_conda_build_dir --help  # [win]
