package:
    name: obvious-ci
    version: 0.5.0

source:
    url: https://github.com/pelson/Obvious-CI/archive/v0.5.0.tar.gz
    fn: obvious-ci_v0.5.0.tar.gz 

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - setuptools
        - anaconda-client
        - conda
        - conda-build

test:
  imports:
    - obvci
    - obvci.conda_tools
    - obvci.cli
  commands:
    - unset CONDA_NPY && obvci_conda_build_dir --help  # [not win]
    - obvci_conda_build_dir --help  # [win]
