
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27  
    - CONDA_PY=34  
    - CONDA_PY=35  
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in forge.yml.
    - secure: "LwEI6i8Qu3eI7H5BjhM2Y+ymhooJChEBKCron3T1WcVrjP/2VS19/z5s9e4m9C9lXANA6kjcNpuSkeycqZqEDY3wBziupgqPCDcQfXM2ow1vGZUoHleGGWSysn0DHyPnhVtOJ7PC9Q+R2kTbbtuDHKkYD0oilt2vSPJf71gHVN01IYaQccUZD7geYSgSCz5Weli1GYW12Z4lsT1aOJB5SL7tS94uAQBTzFJoWpT1gkD+8riQTe+gxfz698O8wfpvV5xNu8dKilbn/ASltdLLOKc+a8f7BFWv1qrMfihf33Q39/IEfxunqf9RtByuUdKTrw6hfDO4/NP0eQnOSHGhDiY5SIcSb7jiMPW7xrjrRQmIfwjmL6cA8hPNqJJMBffqZwFzDxk3DyrTRIjWjA0QPZtQPjfFiEpc4o3ZHilxWurd/CRvEOQllWWa4PWiJL4kWot66Ja8L24da6jNy1QU/qT74v/XdOKCdzO9maoGrVP3v0j5lMoz4WBUk+k6UA+udG+cRkeXvVeislR8daV0ewO7Ipr6Wy8ckksIxwmZ8dmHbf4l6U5yQjyqh8/0Hoos7M411yOS+x2bnd2R2oNY9qUqrH8cwtF+XFIgsuGuAUCH+mvdXNsl3pYqBtlVdFBA5Ra3Dd7pQKBqQiiI1gGJG+bPhi+4Gqkc+CTcCmUAQ3c="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
